### ISSUE TITLE
Watch the bidirectional Falco Outputs 

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/client-rs#15]
**Motivation**

Because of https://github.com/falcosecurity/falco/pull/1241 this Rust gRPC client for Falco needs to adapt to the new API and schema definitions.

See the PR on client-go for reference https://github.com/falcosecurity/client-go/pull/45
**Feature**

- Generate the new API from the new protobuf files.
- Provide a watch functionality that uses the new `falco.outputs.service/sub` bidirectional API.

**Comment by leodido** [comment]
Implement together or after #14
